name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Use the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build
        run: |
          nix develop -c bash -c "exit 0"
